# Generated by Django 4.1.3 on 2023-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_done", models.BooleanField(default=False)),
            ],
        ),
    ]
